# Generated by Django 4.1.6 on 2023-02-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prophetv2', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
