# Generated by Django 4.1.6 on 2023-02-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prophetv2', '0008_stockinfo_teststockinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teststockinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='teststockinfo',
            name='tradingName',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
