# Generated by Django 4.1.6 on 2023-02-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prophetv2', '0009_remove_teststockinfo_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestStockInfo',
        ),
    ]
