# Generated by Django 4.1.6 on 2023-02-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prophetv2', '0011_teststockinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestStockInfo',
        ),
    ]
