# Generated by Django 4.1.6 on 2023-02-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prophetv2', '0016_alter_stockinfo_gtiscore_alter_stockinfo_lastprice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockInfo',
        ),
    ]
