# Generated by Django 4.1.6 on 2023-02-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prophetv2', '0018_stockinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='yieldPercent',
            field=models.FloatField(blank=True),
        ),
    ]
