# Generated by Django 4.1.6 on 2023-02-16 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prophetv2', '0020_alter_stockinfo_gtiscore_alter_stockinfo_lastprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'unique_together': {('name', 'ticker')},
            },
        ),
        migrations.CreateModel(
            name='StockSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prophetv2.profile')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prophetv2.stocks')),
            ],
        ),
        migrations.CreateModel(
            name='StockOwned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prophetv2.profile')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prophetv2.stocks')),
            ],
        ),
    ]
