# Generated by Django 4.1.6 on 2023-02-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prophetv2', '0021_stocks_stocksold_stockowned'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='risk_level',
            field=models.IntegerField(default=0),
        ),
    ]
