# Generated by Django 4.1.6 on 2023-02-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prophetv2', '0026_stockowned_unique_stock_owned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockowned',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocksold',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
