# Generated by Django 4.1.6 on 2023-02-21 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prophetv2', '0027_alter_stockowned_quantity_alter_stocksold_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksold',
            name='stock_owned',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='prophetv2.stockowned'),
        ),
        migrations.AlterField(
            model_name='stockowned',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
