# Generated by Django 4.1.6 on 2023-02-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prophetv2', '0028_stocksold_stock_owned_alter_stockowned_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='risklevel',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3),
        ),
    ]
