# Generated by Django 4.1.6 on 2023-02-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prophetv2', '0030_remove_profile_risklevel_profile_risk_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='risk_level',
            field=models.IntegerField(choices=[(1, 'Lv.1 Low'), (2, 'Lv.2 Moderate'), (3, 'Lv.3 Medium'), (4, 'Lv.4 High'), (5, 'Lv.5 Very High')], default=3),
        ),
    ]
