# Generated by Django 4.1.6 on 2023-02-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prophetv2', '0033_alter_profile_risk_level'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stocksold',
            constraint=models.UniqueConstraint(fields=('profile', 'stock', 'sell_price'), name='unique_stock_sold'),
        ),
        migrations.AddConstraint(
            model_name='stocksold',
            constraint=models.UniqueConstraint(condition=models.Q(('sold_at', None)), fields=('profile', 'stock'), name='unique_stock_sold_null'),
        ),
    ]
